#!/usr/bin/env python3
if __name__ == "__main__": # Indica que inicia el programa principal
 contador = 0
 while contador < 5: # Bucle while
  print(contador)
  contador += 1
 for i in range(5): # Bucle For
  print(i)
